### ISSUE TITLE
[FEAT] MongoDB database connect

### ISSUE THREAD

**Issue by hellofaizan** [hellofaizan/yearprogress#1]
**What's the issue?**
- Bot works fine, runs after every 4 days and sends message but the issue is every time bot goes offline. I have to rerun the `/setup channel name:` command.

**How can be fixed!**
- If we connect it to mongodb, where we can save the server name and channel I'd in which the `/setup` command was used, then in future if the bot goes offline it will automatically start sending messages to those channels without manually running the setup command again

![Screenshot_2023-08-27-09-24-04-15_572064f74bd5f9fa804b05334aa4f912.jpg](https://github.com/hellofaizan/yearprogress/assets/84437051/8d8e76ed-3a8e-4a95-a213-8bb23728b702)

**Comment by vishesh-hue** [comment]
Use MongoDB for Data Storage:

Set up a MongoDB database where you can store essential information such as server names and channel IDs associated with the /setup command.
Store Setup Information:

When a user runs the /setup command, store the server name and channel ID in your MongoDB database along with any other relevant data.
Bot Initialization:

When your bot starts up or is restarted, have it connect to the MongoDB database to retrieve the stored server and channel information.
Automate Message Sending:

Modify your bot's logic to automatically send messages to the specified channels without needing manual intervention each time it restarts.
Use the retrieved server and channel information to send messages at the appropriate times.
Error Handling:

Implement error handling to ensure that your bot can handle unexpected situations, such as connection issues with the MongoDB database.
Here's a simplified example of how you might structure the data in your MongoDB database:

json
{
  "_id": ObjectId("unique_document_id"),
  "serverId": "your_server_id",
  "channelId": "your_channel_id"
}
When your bot starts, it can query the database for documents like the one above and use the server and channel information to send messages.

By using MongoDB or a similar database system, you can persistently store the necessary configuration data, making your bot more robust and reducing the need for manual setup after each restart.

**Comment by hellofaizan** [comment]
I just managed to do that. Check the latest comments. I forgot to close this issue. Sorry for the inconvenience and thanks for the response @vishesh-hue

**Comment by hellofaizan** [comment]
Want to try bot or discuss about features. Join discord https://discord.com/invite/vUHMxPvege
